// frontend/src/lib/components/Sidebar.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { goto } from '$app/navigation';
	import { user } from '../stores/auth';
	import { dashboards, loadDashboards } from '../stores/dashboards';
	import {
		conversationList,
		currentSessionId,
		loadConversationList,
		switchConversation,
		startNewConversation,
		deleteConversation,
		renameConversation
	} from '../stores/conversation';
	import { chartSessionId, loadChartConversation } from '../stores/chart';
	import { tables, loadSchema } from '../stores/schema';
	import { logout, deleteConversation as apiDeleteConversation } from '../api';
	import type { ConversationSummary } from '../types';

	export let currentPath: string = '/app';

	let showDashboards = true;
	let showConversations = true;
	let showData = false;
	let editingId: number | null = null;
	let editingTitle = '';

	onMount(() => {
		loadDashboards();
		loadConversationList();
		loadSchema();
	});

	function toggleData() {
		showData = !showData;
	}

	function handleLogout() {
		logout();
	}

	function toggleDashboards() {
		showDashboards = !showDashboards;
	}

	function toggleConversations() {
		showConversations = !showConversations;
	}

	async function handleSwitchConversation(conv: ConversationSummary) {
		if (conv.conversation_type === 'chart') {
			// For chart conversations, navigate to the chart page and load that conversation
			await loadChartConversation(conv.id);
			goto('/app/charts/new');
		} else {
			// For dashboard conversations, use the existing behavior
			await switchConversation(conv.id);
			goto('/app');
		}
	}

	async function handleNewConversation() {
		await startNewConversation();
	}

	async function handleDeleteConversation(event: Event, conv: ConversationSummary) {
		event.stopPropagation();
		if (confirm('Delete this conversation?')) {
			if (conv.conversation_type === 'chart') {
				// For chart conversations, delete directly
				await apiDeleteConversation(conv.id);
				await loadConversationList();
			} else {
				await deleteConversation(conv.id);
			}
		}
	}

	function startEditing(event: Event, sessionId: number, currentTitle: string | null) {
		event.stopPropagation();
		editingId = sessionId;
		editingTitle = currentTitle || '';
	}

	async function saveEdit(sessionId: number) {
		if (editingTitle.trim()) {
			await renameConversation(sessionId, editingTitle.trim());
		}
		editingId = null;
		editingTitle = '';
	}

	function cancelEdit() {
		editingId = null;
		editingTitle = '';
	}

	function handleEditKeydown(event: KeyboardEvent, sessionId: number) {
		if (event.key === 'Enter') {
			saveEdit(sessionId);
		} else if (event.key === 'Escape') {
			cancelEdit();
		}
	}

	function formatDate(dateStr: string): string {
		const date = new Date(dateStr);
		const now = new Date();
		const diffMs = now.getTime() - date.getTime();
		const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24));

		if (diffDays === 0) return 'Today';
		if (diffDays === 1) return 'Yesterday';
		if (diffDays < 7) return `${diffDays} days ago`;
		return date.toLocaleDateString();
	}

	const navItems = [
		{ path: '/app', label: 'Chat', icon: '>' },
		{ path: '/app/charts', label: 'Charts', icon: '~' },
		{ path: '/app/dashboards', label: 'Dashboards', icon: '#' },
		{ path: '/app/settings', label: 'Settings', icon: '*' }
	];
</script>

<aside class="w-64 h-full bg-terminal-surface border-r border-terminal-border flex flex-col">
	<!-- Logo -->
	<div class="p-4 border-b border-terminal-border">
		<h1 class="text-terminal-accent font-bold text-xl tracking-widest">
			STORY<span class="inline-block w-2 h-5 bg-terminal-accent ml-1 align-middle cursor-blink"></span><span class="inline-block w-2 h-5 bg-terminal-accent ml-0.5 align-middle cursor-blink"></span>
		</h1>
		<p class="text-terminal-dim text-xs mt-1">AI-native analytics.</p>
	</div>

	<!-- Navigation -->
	<nav class="flex-1 p-4">
		<ul class="space-y-1">
			{#each navItems as item}
				<li>
					<a
						href={item.path}
						class="flex items-center gap-2 px-3 py-2 rounded transition-colors
                           {currentPath === item.path
							? 'bg-terminal-border text-terminal-accent'
							: 'text-terminal-text hover:bg-terminal-border'}"
					>
						<span class="text-terminal-amber">{item.icon}</span>
						<span>{item.label}</span>
					</a>
				</li>
			{/each}
		</ul>

		<!-- Conversations list -->
		<div class="mt-6">
			<div class="flex items-center justify-between mb-2">
				<button
					on:click={toggleConversations}
					class="flex items-center gap-2 text-terminal-dim text-sm hover:text-terminal-text transition-colors"
				>
					<span class="transform transition-transform {showConversations ? 'rotate-90' : ''}"
						>{'>'}</span
					>
					<span>Conversations</span>
				</button>
				<button
					on:click={handleNewConversation}
					class="text-terminal-accent hover:text-terminal-text text-sm transition-colors"
					title="New conversation"
				>
					+
				</button>
			</div>

			{#if showConversations}
				<ul class="ml-4 space-y-1 max-h-48 overflow-y-auto">
					{#if $conversationList.length === 0}
						<li class="text-terminal-dim text-xs py-1">No conversations yet</li>
					{:else}
						{#each $conversationList as conv}
							<li class="group flex items-center justify-between">
								{#if editingId === conv.id}
									<input
										type="text"
										bind:value={editingTitle}
										on:keydown={(e) => handleEditKeydown(e, conv.id)}
										on:blur={() => saveEdit(conv.id)}
										class="text-sm py-0.5 px-1 flex-1 bg-terminal-bg border border-terminal-accent rounded text-terminal-text outline-none"
										autofocus
									/>
								{:else}
									<button
										on:click={() => handleSwitchConversation(conv)}
										on:dblclick={(e) => startEditing(e, conv.id, conv.title)}
										class="text-sm truncate py-1 flex-1 text-left transition-colors flex items-center gap-1
	                                        {($currentSessionId === conv.id && conv.conversation_type === 'dashboard') ||
												($chartSessionId === conv.id && conv.conversation_type === 'chart')
											? 'text-terminal-accent'
											: 'text-terminal-dim hover:text-terminal-text'}"
										title="Double-click to rename"
									>
										{#if conv.conversation_type === 'chart'}
											<span class="text-terminal-amber text-xs" title="Chart conversation">~</span>
										{:else}
											<span class="text-terminal-dim text-xs">#</span>
										{/if}
										<span class="truncate">{conv.title || 'New conversation'}</span>
									</button>
									<button
										on:click={(e) => handleDeleteConversation(e, conv)}
										class="text-terminal-dim hover:text-terminal-red text-xs opacity-0 group-hover:opacity-100 transition-opacity px-1"
										title="Delete conversation"
									>
										×
									</button>
								{/if}
							</li>
						{/each}
					{/if}
				</ul>
			{/if}
		</div>

		<!-- Dashboard list -->
		<div class="mt-6">
			<button
				on:click={toggleDashboards}
				class="flex items-center gap-2 text-terminal-dim text-sm hover:text-terminal-text transition-colors w-full"
			>
				<span class="transform transition-transform {showDashboards ? 'rotate-90' : ''}"
					>{'>'}</span
				>
				<span>Recent Dashboards</span>
			</button>

			{#if showDashboards}
				<ul class="mt-2 ml-4 space-y-1">
					{#if $dashboards.length === 0}
						<li class="text-terminal-dim text-xs py-1">No dashboards yet</li>
					{:else}
						{#each $dashboards.slice(0, 5) as dashboard}
							<li>
								<a
									href={dashboard.url}
									target="_blank"
									rel="noopener noreferrer"
									class="text-sm text-terminal-dim hover:text-terminal-accent truncate block py-1"
									title={dashboard.title}
								>
									{dashboard.title}
								</a>
							</li>
						{/each}
						{#if $dashboards.length > 5}
							<li>
								<a href="/app/dashboards" class="text-xs text-terminal-amber hover:underline">
									View all ({$dashboards.length})
								</a>
							</li>
						{/if}
					{/if}
				</ul>
			{/if}
		</div>

		<!-- Available Data -->
		<div class="mt-6">
			<button
				on:click={toggleData}
				class="flex items-center gap-2 text-terminal-dim text-sm hover:text-terminal-text transition-colors w-full"
			>
				<span class="transform transition-transform {showData ? 'rotate-90' : ''}"
					>{'>'}</span
				>
				<span>Available Data</span>
			</button>

			{#if showData}
				<ul class="mt-2 ml-4 space-y-1 max-h-48 overflow-y-auto">
					{#if $tables.length === 0}
						<li class="text-terminal-dim text-xs py-1">No tables found</li>
					{:else}
						{#each $tables as table}
							<li class="group">
								<details class="text-sm">
									<summary class="text-terminal-dim hover:text-terminal-text cursor-pointer py-1 list-none flex items-center gap-1">
										<span class="text-terminal-amber text-xs">+</span>
										<span class="truncate">{table.name}</span>
										<span class="text-terminal-dim text-xs">({table.columns.length})</span>
									</summary>
									<ul class="ml-4 text-xs text-terminal-dim space-y-0.5 pb-1">
										{#each table.columns.slice(0, 8) as column}
											<li class="truncate" title="{column.name}: {column.type}">
												<span class="text-terminal-text">{column.name}</span>
												<span class="text-terminal-dim ml-1">{column.type}</span>
											</li>
										{/each}
										{#if table.columns.length > 8}
											<li class="text-terminal-dim italic">
												+{table.columns.length - 8} more columns
											</li>
										{/if}
									</ul>
								</details>
							</li>
						{/each}
					{/if}
				</ul>
			{/if}
		</div>
	</nav>

	<!-- User info -->
	<div class="p-4 border-t border-terminal-border group/user">
		{#if $user}
			<div class="flex items-center justify-between">
				<div class="truncate">
					<p class="text-terminal-text text-sm truncate">{$user.name}</p>
					<p class="text-terminal-dim text-xs truncate">{$user.email}</p>
				</div>
				<button
					on:click={handleLogout}
					class="text-terminal-dim hover:text-terminal-red text-xs transition-all opacity-0 group-hover/user:opacity-100"
				>
					Log out
				</button>
			</div>
		{/if}
	</div>
</aside>

// app/src/components/layout/Sidebar.tsx
/**
 * Sidebar component.
 * Navigation, conversation history, and dashboard list.
 */

import { useState, useEffect } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { useConversationStore } from '../../stores/conversationStore'
import type { ConversationSummary } from '../../types/conversation'

// Navigation items
const NAV_ITEMS = [
  { path: '/chat', label: 'Chat', icon: '>' },
  { path: '/charts', label: 'Charts', icon: '~' },
  { path: '/dashboards', label: 'Dashboards', icon: '#' },
  { path: '/settings', label: 'Settings', icon: '*' },
]

export function Sidebar() {
  const location = useLocation()
  const navigate = useNavigate()
  const {
    conversationList,
    dashboardList,
    currentSessionId,
    user,
    loadConversationList,
    loadDashboards,
    loadUser,
    switchConversation,
    startNewConversation,
    deleteConversation,
    renameConversation,
    logout,
  } = useConversationStore()

  const [showConversations, setShowConversations] = useState(true)
  const [showDashboards, setShowDashboards] = useState(true)
  const [editingId, setEditingId] = useState<number | null>(null)
  const [editingTitle, setEditingTitle] = useState('')

  // Load data on mount
  useEffect(() => {
    loadUser()
    loadConversationList()
    loadDashboards()
  }, [loadUser, loadConversationList, loadDashboards])

  // Handle conversation switch
  const handleSwitchConversation = async (conv: ConversationSummary) => {
    if (conv.conversation_type === 'chart') {
      // For chart conversations, navigate to chart page
      navigate('/charts/new')
    } else {
      await switchConversation(conv.id)
      navigate('/chat')
    }
  }

  // Handle delete
  const handleDelete = async (e: React.MouseEvent, conv: ConversationSummary) => {
    e.stopPropagation()
    if (confirm('Delete this conversation?')) {
      await deleteConversation(conv.id)
    }
  }

  // Handle rename
  const startEditing = (e: React.MouseEvent, id: number, title: string | null) => {
    e.stopPropagation()
    setEditingId(id)
    setEditingTitle(title || '')
  }

  const saveEdit = async (id: number) => {
    if (editingTitle.trim()) {
      await renameConversation(id, editingTitle.trim())
    }
    setEditingId(null)
    setEditingTitle('')
  }

  const cancelEdit = () => {
    setEditingId(null)
    setEditingTitle('')
  }

  const handleEditKeyDown = (e: React.KeyboardEvent, id: number) => {
    if (e.key === 'Enter') {
      saveEdit(id)
    } else if (e.key === 'Escape') {
      cancelEdit()
    }
  }

  return (
    <aside
      style={{
        width: '256px',
        height: '100%',
        backgroundColor: 'var(--color-gray-50)',
        borderRight: '1px solid var(--color-gray-200)',
        display: 'flex',
        flexDirection: 'column',
      }}
    >
      {/* Logo */}
      <div
        style={{
          padding: 'var(--space-4)',
          borderBottom: '1px solid var(--color-gray-200)',
        }}
      >
        <h1
          style={{
            color: 'var(--color-primary)',
            fontWeight: 'var(--font-bold)' as unknown as number,
            fontSize: 'var(--text-xl)',
            letterSpacing: '0.1em',
            margin: 0,
          }}
        >
          STORY
          <span
            style={{
              display: 'inline-block',
              width: '8px',
              height: '20px',
              backgroundColor: 'var(--color-primary)',
              marginLeft: '4px',
              verticalAlign: 'middle',
              animation: 'blink 1s step-end infinite',
            }}
          />
        </h1>
        <p
          style={{
            color: 'var(--color-gray-500)',
            fontSize: 'var(--text-xs)',
            marginTop: 'var(--space-1)',
          }}
        >
          AI-native analytics.
        </p>
      </div>

      {/* Navigation */}
      <nav style={{ flex: 1, padding: 'var(--space-4)', overflowY: 'auto' }}>
        <ul style={{ listStyle: 'none', margin: 0, padding: 0 }}>
          {NAV_ITEMS.map((item) => (
            <li key={item.path} style={{ marginBottom: 'var(--space-1)' }}>
              <a
                href={item.path}
                onClick={(e) => {
                  e.preventDefault()
                  navigate(item.path)
                }}
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: 'var(--space-2)',
                  padding: 'var(--space-2) var(--space-3)',
                  borderRadius: 'var(--radius-md)',
                  textDecoration: 'none',
                  transition: 'all var(--transition-fast)',
                  backgroundColor:
                    location.pathname === item.path
                      ? 'var(--color-gray-200)'
                      : 'transparent',
                  color:
                    location.pathname === item.path
                      ? 'var(--color-primary)'
                      : 'var(--color-gray-700)',
                }}
              >
                <span style={{ color: 'var(--color-warning)', fontFamily: 'var(--font-mono)' }}>
                  {item.icon}
                </span>
                <span>{item.label}</span>
              </a>
            </li>
          ))}
        </ul>

        {/* Conversations */}
        <div style={{ marginTop: 'var(--space-6)' }}>
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              marginBottom: 'var(--space-2)',
            }}
          >
            <button
              onClick={() => setShowConversations(!showConversations)}
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: 'var(--space-2)',
                color: 'var(--color-gray-500)',
                fontSize: 'var(--text-sm)',
                background: 'none',
                border: 'none',
                cursor: 'pointer',
                padding: 0,
              }}
            >
              <span
                style={{
                  transform: showConversations ? 'rotate(90deg)' : 'none',
                  transition: 'transform var(--transition-fast)',
                }}
              >
                {'>'}
              </span>
              <span>Conversations</span>
            </button>
            <button
              onClick={startNewConversation}
              style={{
                color: 'var(--color-primary)',
                fontSize: 'var(--text-sm)',
                background: 'none',
                border: 'none',
                cursor: 'pointer',
              }}
              title="New conversation"
            >
              +
            </button>
          </div>

          {showConversations && (
            <ul
              style={{
                listStyle: 'none',
                margin: 0,
                padding: 0,
                marginLeft: 'var(--space-4)',
                maxHeight: '192px',
                overflowY: 'auto',
              }}
            >
              {conversationList.length === 0 ? (
                <li
                  style={{
                    color: 'var(--color-gray-400)',
                    fontSize: 'var(--text-xs)',
                    padding: 'var(--space-1) 0',
                  }}
                >
                  No conversations yet
                </li>
              ) : (
                conversationList.map((conv) => (
                  <li
                    key={conv.id}
                    style={{
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'space-between',
                    }}
                  >
                    {editingId === conv.id ? (
                      <input
                        type="text"
                        value={editingTitle}
                        onChange={(e) => setEditingTitle(e.target.value)}
                        onKeyDown={(e) => handleEditKeyDown(e, conv.id)}
                        onBlur={() => saveEdit(conv.id)}
                        autoFocus
                        style={{
                          fontSize: 'var(--text-sm)',
                          padding: '2px 4px',
                          flex: 1,
                          backgroundColor: 'white',
                          border: '1px solid var(--color-primary)',
                          borderRadius: 'var(--radius-sm)',
                          outline: 'none',
                        }}
                      />
                    ) : (
                      <>
                        <button
                          onClick={() => handleSwitchConversation(conv)}
                          onDoubleClick={(e) => startEditing(e, conv.id, conv.title)}
                          style={{
                            flex: 1,
                            textAlign: 'left',
                            fontSize: 'var(--text-sm)',
                            padding: 'var(--space-1) 0',
                            background: 'none',
                            border: 'none',
                            cursor: 'pointer',
                            color:
                              currentSessionId === conv.id
                                ? 'var(--color-primary)'
                                : 'var(--color-gray-500)',
                            display: 'flex',
                            alignItems: 'center',
                            gap: 'var(--space-1)',
                            overflow: 'hidden',
                          }}
                          title="Double-click to rename"
                        >
                          <span
                            style={{
                              color:
                                conv.conversation_type === 'chart'
                                  ? 'var(--color-warning)'
                                  : 'var(--color-gray-400)',
                              fontSize: 'var(--text-xs)',
                            }}
                          >
                            {conv.conversation_type === 'chart' ? '~' : '#'}
                          </span>
                          <span
                            style={{
                              overflow: 'hidden',
                              textOverflow: 'ellipsis',
                              whiteSpace: 'nowrap',
                            }}
                          >
                            {conv.title || 'New conversation'}
                          </span>
                        </button>
                        <button
                          onClick={(e) => handleDelete(e, conv)}
                          style={{
                            color: 'var(--color-gray-400)',
                            fontSize: 'var(--text-xs)',
                            background: 'none',
                            border: 'none',
                            cursor: 'pointer',
                            opacity: 0,
                            transition: 'opacity var(--transition-fast)',
                            padding: '0 var(--space-1)',
                          }}
                          onMouseEnter={(e) => {
                            e.currentTarget.style.opacity = '1'
                            e.currentTarget.style.color = 'var(--color-error)'
                          }}
                          onMouseLeave={(e) => {
                            e.currentTarget.style.opacity = '0'
                            e.currentTarget.style.color = 'var(--color-gray-400)'
                          }}
                          title="Delete conversation"
                        >
                          x
                        </button>
                      </>
                    )}
                  </li>
                ))
              )}
            </ul>
          )}
        </div>

        {/* Dashboards */}
        <div style={{ marginTop: 'var(--space-6)' }}>
          <button
            onClick={() => setShowDashboards(!showDashboards)}
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: 'var(--space-2)',
              color: 'var(--color-gray-500)',
              fontSize: 'var(--text-sm)',
              background: 'none',
              border: 'none',
              cursor: 'pointer',
              padding: 0,
              width: '100%',
              marginBottom: 'var(--space-2)',
            }}
          >
            <span
              style={{
                transform: showDashboards ? 'rotate(90deg)' : 'none',
                transition: 'transform var(--transition-fast)',
              }}
            >
              {'>'}
            </span>
            <span>Recent Dashboards</span>
          </button>

          {showDashboards && (
            <ul
              style={{
                listStyle: 'none',
                margin: 0,
                padding: 0,
                marginLeft: 'var(--space-4)',
              }}
            >
              {dashboardList.length === 0 ? (
                <li
                  style={{
                    color: 'var(--color-gray-400)',
                    fontSize: 'var(--text-xs)',
                    padding: 'var(--space-1) 0',
                  }}
                >
                  No dashboards yet
                </li>
              ) : (
                dashboardList.slice(0, 5).map((dashboard) => (
                  <li key={dashboard.id}>
                    <a
                      href={dashboard.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      style={{
                        display: 'block',
                        fontSize: 'var(--text-sm)',
                        color: 'var(--color-gray-500)',
                        padding: 'var(--space-1) 0',
                        textDecoration: 'none',
                        overflow: 'hidden',
                        textOverflow: 'ellipsis',
                        whiteSpace: 'nowrap',
                      }}
                      title={dashboard.title}
                    >
                      {dashboard.title}
                    </a>
                  </li>
                ))
              )}
              {dashboardList.length > 5 && (
                <li>
                  <a
                    href="/dashboards"
                    onClick={(e) => {
                      e.preventDefault()
                      navigate('/dashboards')
                    }}
                    style={{
                      fontSize: 'var(--text-xs)',
                      color: 'var(--color-warning)',
                      textDecoration: 'none',
                    }}
                  >
                    View all ({dashboardList.length})
                  </a>
                </li>
              )}
            </ul>
          )}
        </div>
      </nav>

      {/* User info */}
      {user && (
        <div
          style={{
            padding: 'var(--space-4)',
            borderTop: '1px solid var(--color-gray-200)',
          }}
        >
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
            }}
          >
            <div style={{ overflow: 'hidden' }}>
              <p
                style={{
                  fontSize: 'var(--text-sm)',
                  color: 'var(--color-gray-700)',
                  margin: 0,
                  overflow: 'hidden',
                  textOverflow: 'ellipsis',
                  whiteSpace: 'nowrap',
                }}
              >
                {user.name}
              </p>
              <p
                style={{
                  fontSize: 'var(--text-xs)',
                  color: 'var(--color-gray-500)',
                  margin: 0,
                  overflow: 'hidden',
                  textOverflow: 'ellipsis',
                  whiteSpace: 'nowrap',
                }}
              >
                {user.email}
              </p>
            </div>
            <button
              onClick={logout}
              style={{
                fontSize: 'var(--text-xs)',
                color: 'var(--color-gray-400)',
                background: 'none',
                border: 'none',
                cursor: 'pointer',
              }}
            >
              Log out
            </button>
          </div>
        </div>
      )}

      {/* Blink animation */}
      <style>{`
        @keyframes blink {
          50% { opacity: 0; }
        }
      `}</style>
    </aside>
  )
}
