// frontend/src/lib/components/Message.svelte
<script lang="ts">
	import { marked } from 'marked';
	import { createEventDispatcher } from 'svelte';
	import type { ExtendedMessage } from '../stores/conversation';

	export let message: ExtendedMessage;
	export let disabled: boolean = false;

	const dispatch = createEventDispatcher<{
		optionSelect: { value: string };
		actionClick: { id: string };
	}>();

	// Configure marked for terminal-friendly output with links opening in new tabs
	const renderer = new marked.Renderer();
	renderer.link = (href, title, text) => {
		const titleAttr = title ? ` title="${title}"` : '';
		return `<a href="${href}"${titleAttr} target="_blank" rel="noopener noreferrer">${text}</a>`;
	};

	marked.setOptions({
		breaks: true,
		gfm: true,
		renderer
	});

	$: renderedContent = message.role === 'assistant' ? marked(message.content) : message.content;

	function handleOptionClick(value: string) {
		dispatch('optionSelect', { value });
	}

	function handleActionClick(id: string) {
		dispatch('actionClick', { id });
	}
</script>

<div class="py-3 {message.role === 'user' ? 'border-l-2 border-terminal-accent pl-4' : 'pl-4'}">
	<div class="flex items-start gap-3">
		{#if message.role === 'user'}
			<span class="text-terminal-accent font-bold shrink-0">{'>'}</span>
		{:else}
			<span class="text-terminal-amber font-bold shrink-0">$</span>
		{/if}

		<div class="flex-1 overflow-hidden">
			{#if message.role === 'user'}
				<p class="text-terminal-text whitespace-pre-wrap">{message.content}</p>
			{:else}
				<div class="markdown-content text-terminal-text prose prose-invert max-w-none">
					{@html renderedContent}
				</div>

				<!-- Clarifying Options -->
				{#if message.clarifying_options && message.clarifying_options.length > 0}
					<div class="mt-3 flex flex-wrap gap-2">
						{#each message.clarifying_options as option}
							<button
								type="button"
								on:click={() => handleOptionClick(option.value)}
								class="px-3 py-1.5 text-sm bg-terminal-surface border border-terminal-border rounded
                                       hover:border-terminal-accent hover:text-terminal-accent
                                       transition-colors cursor-pointer"
							>
								{option.label}
							</button>
						{/each}
					</div>
				{/if}

				<!-- Action Buttons -->
				{#if message.action_buttons && message.action_buttons.length > 0}
					<div class="mt-4 flex flex-wrap gap-2">
						{#each message.action_buttons as button}
							{@const isViewDashboard = button.id.startsWith('view_dashboard:')}
							{@const buttonDisabled = disabled && !isViewDashboard}
							<button
								type="button"
								on:click={() => handleActionClick(button.id)}
								disabled={buttonDisabled}
								class="px-4 py-2 text-sm font-medium rounded transition-colors
									{buttonDisabled
									? 'opacity-50 cursor-not-allowed'
									: 'cursor-pointer'}
									{button.style === 'primary'
									? 'bg-terminal-accent text-terminal-bg' + (buttonDisabled ? '' : ' hover:bg-terminal-accent/80')
									: 'bg-terminal-surface border border-terminal-border' + (buttonDisabled ? '' : ' hover:border-terminal-accent hover:text-terminal-accent')}"
							>
								{button.label}
							</button>
						{/each}
					</div>
				{/if}
			{/if}
		</div>
	</div>
</div>

// app/src/components/chat/Message.tsx
/**
 * Message component for chat UI.
 * Renders user and assistant messages with markdown support.
 */

import ReactMarkdown from 'react-markdown'
import type { ExtendedMessage, ActionButton, ClarifyingOption } from '../../types/conversation'

interface MessageProps {
  message: ExtendedMessage
  disabled?: boolean
  onOptionSelect?: (value: string) => void
  onActionClick?: (id: string) => void
}

export function Message({
  message,
  disabled = false,
  onOptionSelect,
  onActionClick,
}: MessageProps) {
  const isUser = message.role === 'user'

  return (
    <div
      className="fade-in"
      style={{
        padding: 'var(--space-3) 0',
        borderLeft: isUser ? '2px solid var(--color-primary)' : 'none',
        paddingLeft: 'var(--space-4)',
      }}
    >
      <div style={{ display: 'flex', alignItems: 'flex-start', gap: 'var(--space-3)' }}>
        {/* Role indicator */}
        <span
          style={{
            fontWeight: 'var(--font-bold)' as unknown as number,
            flexShrink: 0,
            color: isUser ? 'var(--color-primary)' : 'var(--color-warning)',
            fontFamily: 'var(--font-mono)',
          }}
        >
          {isUser ? '>' : '$'}
        </span>

        {/* Message content */}
        <div style={{ flex: 1, overflow: 'hidden' }}>
          {isUser ? (
            <p
              style={{
                margin: 0,
                whiteSpace: 'pre-wrap',
                color: 'var(--color-gray-800)',
              }}
            >
              {message.content}
            </p>
          ) : (
            <>
              {/* Markdown content */}
              <div className="markdown-content">
                <ReactMarkdown
                  components={{
                    a: ({ href, children }) => (
                      <a
                        href={href}
                        target="_blank"
                        rel="noopener noreferrer"
                        style={{ color: 'var(--color-primary)' }}
                      >
                        {children}
                      </a>
                    ),
                    p: ({ children }) => (
                      <p style={{ margin: '0 0 var(--space-2) 0' }}>{children}</p>
                    ),
                    ul: ({ children }) => (
                      <ul
                        style={{
                          margin: '0 0 var(--space-2) 0',
                          paddingLeft: 'var(--space-5)',
                        }}
                      >
                        {children}
                      </ul>
                    ),
                    li: ({ children }) => (
                      <li style={{ marginBottom: 'var(--space-1)' }}>{children}</li>
                    ),
                    strong: ({ children }) => (
                      <strong style={{ fontWeight: 'var(--font-semibold)' as unknown as number }}>
                        {children}
                      </strong>
                    ),
                    code: ({ children }) => (
                      <code
                        style={{
                          fontFamily: 'var(--font-mono)',
                          backgroundColor: 'var(--color-gray-100)',
                          padding: '0.125rem 0.25rem',
                          borderRadius: 'var(--radius-sm)',
                          fontSize: 'var(--text-sm)',
                        }}
                      >
                        {children}
                      </code>
                    ),
                  }}
                >
                  {message.content}
                </ReactMarkdown>
              </div>

              {/* Clarifying Options */}
              {message.clarifying_options && message.clarifying_options.length > 0 && (
                <ClarifyingOptionsButtons
                  options={message.clarifying_options}
                  disabled={disabled}
                  onSelect={onOptionSelect}
                />
              )}

              {/* Action Buttons */}
              {message.action_buttons && message.action_buttons.length > 0 && (
                <ActionButtons
                  buttons={message.action_buttons}
                  disabled={disabled}
                  onClick={onActionClick}
                />
              )}
            </>
          )}
        </div>
      </div>
    </div>
  )
}

// =============================================================================
// Sub-components
// =============================================================================

interface ClarifyingOptionsButtonsProps {
  options: ClarifyingOption[]
  disabled: boolean
  onSelect?: (value: string) => void
}

function ClarifyingOptionsButtons({
  options,
  disabled,
  onSelect,
}: ClarifyingOptionsButtonsProps) {
  return (
    <div
      style={{
        marginTop: 'var(--space-3)',
        display: 'flex',
        flexWrap: 'wrap',
        gap: 'var(--space-2)',
      }}
    >
      {options.map((option, idx) => (
        <button
          key={idx}
          type="button"
          onClick={() => onSelect?.(option.value)}
          disabled={disabled}
          style={{
            padding: 'var(--space-2) var(--space-3)',
            fontSize: 'var(--text-sm)',
            backgroundColor: 'white',
            border: '1px solid var(--color-gray-300)',
            borderRadius: 'var(--radius-md)',
            cursor: disabled ? 'not-allowed' : 'pointer',
            opacity: disabled ? 0.5 : 1,
            transition: 'all var(--transition-fast)',
          }}
          onMouseEnter={(e) => {
            if (!disabled) {
              e.currentTarget.style.borderColor = 'var(--color-primary)'
              e.currentTarget.style.color = 'var(--color-primary)'
            }
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.borderColor = 'var(--color-gray-300)'
            e.currentTarget.style.color = 'inherit'
          }}
        >
          {option.label}
        </button>
      ))}
    </div>
  )
}

interface ActionButtonsProps {
  buttons: ActionButton[]
  disabled: boolean
  onClick?: (id: string) => void
}

function ActionButtons({ buttons, disabled, onClick }: ActionButtonsProps) {
  return (
    <div
      style={{
        marginTop: 'var(--space-4)',
        display: 'flex',
        flexWrap: 'wrap',
        gap: 'var(--space-2)',
      }}
    >
      {buttons.map((button) => {
        const isViewDashboard = button.id.startsWith('view_dashboard:')
        const buttonDisabled = disabled && !isViewDashboard
        const isPrimary = button.style === 'primary'

        return (
          <button
            key={button.id}
            type="button"
            onClick={() => onClick?.(button.id)}
            disabled={buttonDisabled}
            style={{
              padding: 'var(--space-2) var(--space-4)',
              fontSize: 'var(--text-sm)',
              fontWeight: 'var(--font-medium)' as unknown as number,
              borderRadius: 'var(--radius-md)',
              cursor: buttonDisabled ? 'not-allowed' : 'pointer',
              opacity: buttonDisabled ? 0.5 : 1,
              transition: 'all var(--transition-fast)',
              ...(isPrimary
                ? {
                    backgroundColor: 'var(--color-primary)',
                    color: 'white',
                    border: 'none',
                  }
                : {
                    backgroundColor: 'white',
                    color: 'var(--color-gray-700)',
                    border: '1px solid var(--color-gray-300)',
                  }),
            }}
            onMouseEnter={(e) => {
              if (!buttonDisabled) {
                if (isPrimary) {
                  e.currentTarget.style.backgroundColor = 'var(--color-primary-dark)'
                } else {
                  e.currentTarget.style.borderColor = 'var(--color-primary)'
                  e.currentTarget.style.color = 'var(--color-primary)'
                }
              }
            }}
            onMouseLeave={(e) => {
              if (isPrimary) {
                e.currentTarget.style.backgroundColor = 'var(--color-primary)'
              } else {
                e.currentTarget.style.borderColor = 'var(--color-gray-300)'
                e.currentTarget.style.color = 'var(--color-gray-700)'
              }
            }}
          >
            {button.label}
          </button>
        )
      })}
    </div>
  )
}
